controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Arm
arm_controller:
  ros__parameters:
    joints:
      - lower_arm_joint
      - gripper_hand_left_joint
      - gripper_hand_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity